version: '3.9'

services:
  tasks-localstack:
    image: localstack/localstack:latest
    container_name: tasks-localstack
    env_file:
      - ./utils/docker/env/localstack-dev.env
    ports:
      - "4566:4566"
    volumes:
      - ./src/city-tasks-events/target/city-tasks-events-1.6.0.jar:/var/lib/localstack/city-tasks-events-1.6.0.jar
      - ./utils/docker/localstack/dynamodb/devices.json:/var/lib/localstack/devices.json
      - ./utils/docker/localstack/resources.sh:/etc/localstack/init/ready.d/resources-setup.sh
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - hiperium-network

  tasks-postgres:
    image: postgres:14.4
    container_name: tasks-postgres
    environment:
      - POSTGRES_DB=CityTasksDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - "5432:5432"
    networks:
      - hiperium-network

  tasks-api:
    image: aosolorzano/city-tasks-api:1.6.0
    container_name: tasks-api
    build:
      context: .
      dockerfile: src/city-tasks-api/Dockerfile
    env_file:
      - ./utils/docker/env/tasks-api-dev.env
    depends_on:
      - tasks-localstack
      - tasks-postgres
    ports:
      - "8080:8080"
    networks:
      - hiperium-network

  tasks-proxy:
    image: aosolorzano/city-tasks-proxy:1.6.0
    container_name: tasks-proxy
    build:
      context: .
      dockerfile: src/city-tasks-proxy/Dockerfile
      args:
        envoy_env: dev
    depends_on:
      - tasks-api
    ports:
      - "443:443"
    networks:
      - hiperium-network

networks:
  hiperium-network:
    driver: bridge
