# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[dev]
[dev.global.parameters]
stack_name = "city-tasks-events-dev"

[dev.build.parameters]
cached = false
parallel = true

[dev.validate.parameters]
lint = true

[dev.package.parameters]
resolve_s3 = true

[dev.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true

[dev.sync.parameters]
watch = true

[dev.local_start_api.parameters]
warm_containers = "EAGER"

[dev.local_start_lambda.parameters]
warm_containers = "EAGER"
